### PR TITLE
NX627J: Merge stock init configuration

### PR DESCRIPTION
**Pull request by EvilGodEX**
Load more init files from the vendor partition

### CODE REVIEW

**Comment by gesangtome** [comment]
@EvilGodEX 
Hello, although you merged the vendor's init files, the build system will not install them to the corresponding locations. Can you fix it? thanks you.

**Comment by EvilGodEX** [comment]
@Flowertome I know. Can I consider merging my patches after I add them?

**Comment by gesangtome** [comment]
@EvilGodEX 
Patches are always welcome.

**Comment by EvilGodEX** [comment]
@Flowertome thanks D: )

**Comment by gesangtome** [comment]
@EvilGodEX 
The review will be passed without error.

**Pull request merged**
