### PR TITLE
init: Adjust rc script include order

### PR DESCRIPTION
**Pull request by EvilGodEX**
I think your new rc script should be included in init.extension.rc

### CODE REVIEW

**Comment by gesangtome** [comment]
@EvilGodEX 
Hello, Give your reasons please.

**Comment by EvilGodEX** [comment]
@Flowertome 
I consulted the nubia boot image and found that the content in the newly added rc script was actually obtained from init.rc. Then according to the nubia boot image, init.rc will load and initialize the contents of init.rc itself after loading all other init.*rc. so I think the way to change the order to nubia is more suitable for you to debug, please consider merging my patches.

**Comment by gesangtome** [comment]
@EvilGodEX 
I will decide whether to merge in a review, thanks you.

**Comment by gesangtome** [comment]
@EvilGodEX Seems like a good decision.

**Pull request merged**
